# mc_data.py

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Import rcParams to use Korean fonts.
from matplotlib import rcParams
rcParams["font.family"] = "Malgun Gothic"
rcParams["axes.unicode_minus"] = False

class MCData:
    """This is a class that manipulates the data generated by a series of a Monte Carlo simulation."""
    
    # For example, the method of self.generate_mc_data() in the class of MonteCarlo generates 
    # self.mc_data: {(0,0): {1: 3, 0: 2, -1: 5}, (0, 1): {1: 4, 0: 2, -1: 4}, ... }.
    
    def __init__(self, freq_dist=None, sample_size=None):
        self.freq_dist = freq_dist
        self.sample_size = sample_size
        self.sorted= {}
        # print(f'Data: {self.freq_dist}')
        self.initialize()

        
    def initialize(self):    
        # data = np.random.normal(0, 1, 1000) # 평균 0, 표준편차 1인 데이터 생성
        data = [item[1] for item in self.freq_dist.values()]
        plt.hist(data, bins=30) # 30개의 구간으로 나눔
        plt.xlabel("값")
        plt.ylabel("빈도")
        plt.title("히스토그램")
        plt.show()


        
if __name__ == "__main__":
    
    mcd = MCData()
    mcd.freq_dist = {(0, 0): {1: [0, 100, 0, 52, 0, 0, 0, 0, 0, 0, 72, 0, 66, 100, 100, 0, 100, 0, 0, 0], 0: [1, 0, 100, 0, 1, 1, 0, 0, 0, 1, 28, 100, 34, 0, 0, 1, 0, 0, 0, 0], -1: [99, 0, 0, 48, 99, 99, 100, 100, 100, 99, 0, 0, 0, 0, 0, 99, 0, 100, 100, 100]}, (2, 0): {1: [100, 31, 35, 0, 32, 0, 32, 0, 0, 0, 100, 38, 0, 37, 32, 0, 38, 100, 0, 0], 0: [0, 69, 65, 100, 68, 0, 68, 100, 0, 0, 0, 62, 100, 63, 68, 0, 62, 0, 100, 100], -1: [0, 0, 0, 0, 0, 100, 0, 0, 100, 100, 0, 0, 0, 0, 0, 100, 0, 0, 0, 0]}, (2, 1): {1: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0: [0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1], -1: [100, 99, 99, 99, 100, 99, 99, 99, 99, 99, 100, 99, 100, 100, 99, 99, 100, 99, 99, 99]}, (2, 2): {1: [100, 0, 0, 0, 100, 62, 0, 48, 0, 48, 0, 0, 0, 0, 0, 67, 0, 69, 69, 67], 0: [0, 0, 0, 0, 0, 38, 100, 0, 100, 0, 1, 0, 1, 1, 0, 33, 1, 31, 31, 33], -1: [0, 100, 100, 100, 0, 0, 0, 52, 0, 52, 99, 100, 99, 99, 100, 0, 99, 0, 0, 0]}}
    
    mcd.initialize()