# mc_data.py

class MCData:
    """This is a class that saves the data generated by a series of a Monte Carlo simulation:
    For example, self.mc_data: {(0,0): {1: 3, 0: 2, -1: 5}, (0, 1): {1: 4, 0: 2, -1: 4}, ... }."""
    
    def __init__(self, freq_dist, sample_size):
        self.freq_dist = freq_dist
        self.sample_size = sample_size
        